package com.example.seproject;

public class gali
{
    String galistr;
    gali()
    {
        this.galistr="anal\n" +
            "analannie\n" +
            "analsex\n" +
            "angie\n" +
            "anus\n" +
            "areola\n" +
            "arse\n" +
            "arsehole\n" +
            "ass\n" +
            "assbagger\n" +
            "assblaster\n" +
            "assclown\n" +
            "asscowboy\n" +
            "asses\n" +
            "assfuck\n" +
            "assfucker\n" +
            "asshat\n" +
            "asshole\n" +
            "assholes\n" +
            "asshore\n" +
            "assjacker\n" +
            "assjockey\n" +
            "asskiss\n" +
            "asskisser\n" +
            "assklown\n" +
            "asslick\n" +
            "asslicker\n" +
            "asslover\n" +
            "assman\n" +
            "assmonkey\n" +
            "assmunch\n" +
            "assmuncher\n" +
            "asspacker\n" +
            "asspirate\n" +
            "asspuppies\n" +
            "assranger\n" +
            "asswhore\n" +
            "asswipe\n" +
            "babe\n" +
            "badfuck\n" +
            "balllicker\n" +
            "ballicker\n" +
            "ballsack\n" +
            "balls\n" +
            "bastard \n" +
            "bazonga\n" +
            "bazooms\n" +
            "beast\n" +
            "beastality\n" +
            "beastial\n" +
            "beastiality\n" +
            "beatyourmeat\n" +
            "beaver\n" +
            "bestial\n" +
            "bestiality\n" +
            "biatch\n" +
            "bigass\n" +
            "bigbastard\n" +
            "bigbutt\n" +
            "bisexual\n" +
            "bitch\n" +
            "bitcher\n" +
            "bitches\n" +
            "bitchez\n" +
            "bitchin\n" +
            "bitching\n" +
            "bitchslap\n" +
            "bitchy\n" +
            "blowjob\n" +
            "boang\n" +
            "bogan\n" +
            "bohunk\n" +
            "bollick\n" +
            "bollock\n" +
            "bondage\n" +
            "boner\n" +
            "bong\n" +
            "boob\n" +
            "boobies\n" +
            "boobs\n" +
            "booby\n" +
            "boody\n" +
            "boong\n" +
            "boonga\n" +
            "boonie\n" +
            "booty\n" +
            "bootycall\n" +
            "bountybar\n" +
            "bra\n" +
            "brea5t\n" +
            "breast\n" +
            "breastjob\n" +
            "breastlover\n" +
            "breastman\n" +
            "brothel\n" +
            "bugger\n" +
            "buggered\n" +
            "buggery\n" +
            "bullcrap\n" +
            "bulldike\n" +
            "bulldyke\n" +
            "bullshit\n" +
            "bumblefuck\n" +
            "bumfuck\n" +
            "bunga\n" +
            "bunghole\n" +
            "butchbabes\n" +
            "butchdike\n" +
            "butchdyke\n" +
            "butt\n" +
            "buttbang\n" +
            "butt-bang\n" +
            "buttface\n" +
            "buttfuck\n" +
            "butt-fuck\n" +
            "buttfucker\n" +
            "butt-fucker\n" +
            "buttfuckers\n" +
            "butt-fuckers\n" +
            "butthead\n" +
            "buttman\n" +
            "buttmunch\n" +
            "buttmuncher\n" +
            "buttpirate\n" +
            "buttplug\n" +
            "buttstain\n" +
            "byatch\n" +
            "cacker\n" +
            "cameljockey\n" +
            "cameltoe\n" +
            "cancer\n" +
            "carpetmuncher\n" +
            "carruth\n" +
            "cherrypopper\n" +
            "chickslick\n" +
            "chink\n" +
            "chinky\n" +
            "choad\n" +
            "chode\n" +
            "cigs\n" +
            "clamdigger\n" +
            "clamdiver\n" +
            "clit\n" +
            "clitoris\n" +
            "clogwog\n" +
            "cocaine\n" +
            "cock\n" +
            "cockblock\n" +
            "cockblocker\n" +
            "cockcowboy\n" +
            "cockfight\n" +
            "cockhead\n" +
            "cockknob\n" +
            "cocklicker\n" +
            "cocklover\n" +
            "cocknob\n" +
            "cockqueen\n" +
            "cockrider\n" +
            "cocksman\n" +
            "cocksmith\n" +
            "cocksmoker\n" +
            "cocksucer\n" +
            "cocksuck \n" +
            "cocksucked \n" +
            "cocksucker\n" +
            "cocksucking\n" +
            "cocktease\n" +
            "cocky\n" +
            "cohee\n" +
            "coitus\n" +
            "commie\n" +
            "condom\n" +
            "coolie\n" +
            "cooly\n" +
            "coon\n" +
            "coondog\n" +
            "copulate\n" +
            "cornhole\n" +
            "crabs\n" +
            "crackpipe\n" +
            "crackwhore\n" +
            "crack-whore\n" +
            "crap\n" +
            "crapola\n" +
            "crapper\n" +
            "crappy\n" +
            "creamy\n" +
            "crotch\n" +
            "crotchjockey\n" +
            "crotchmonkey\n" +
            "crotchrot\n" +
            "cumbubble\n" +
            "cumfest\n" +
            "cumjockey\n" +
            "cumm\n" +
            "cummer\n" +
            "cumming\n" +
            "cumquat\n" +
            "cumqueen\n" +
            "cumshot\n" +
            "cunilingus\n" +
            "cunillingus\n" +
            "cunn\n" +
            "cunnilingus\n" +
            "cunntt\n" +
            "cunt\n" +
            "cunteyed\n" +
            "cuntfuck\n" +
            "cuntfucker\n" +
            "cuntlick \n" +
            "cuntlicker \n" +
            "cuntlicking \n" +
            "cuntsucker\n" +
            "cybersex\n" +
            "cyberslimer\n" +
            "darkie\n" +
            "darky\n" +
            "datnigga\n" +
            "deapthroat\n" +
            "deepthroat\n" +
            "defecate\n" +
            "demon\n" +
            "devil\n" +
            "devilworshipper\n" +
            "dick\n" +
            "dickbrain\n" +
            "dickforbrains\n" +
            "dickhead\n" +
            "dickless\n" +
            "dicklick\n" +
            "dicklicker\n" +
            "dickman\n" +
            "dickwad\n" +
            "dickweed\n" +
            "diddle\n" +
            "dike\n" +
            "dildo\n" +
            "dingleberry\n" +
            "dink\n" +
            "dipshit\n" +
            "dipstick\n" +
            "dixiedike\n" +
            "dixiedyke\n" +
            "doggiestyle\n" +
            "doggystyle\n" +
            "dog\n" +
            "dong\n" +
            "doodoo\n" +
            "dope\n" +
            "dragqueen\n" +
            "dragqween\n" +
            "dripdick\n" +
            "drunk\n" +
            "drunken\n" +
            "dumb\n" +
            "dumbass\n" +
            "dumbbitch\n" +
            "dumbfuck\n" +
            "dyke\n" +
            "easyslut\n" +
            "eatballs\n" +
            "eatpussy\n" +
            "ecstacy\n" +
            "ecstasy\n" +
            "ejaculate\n" +
            "ejaculated\n" +
            "ejaculating \n" +
            "ejaculation\n" +
            "erect\n" +
            "erection\n" +
            "evil\n" +
            "excrement\n" +
            "facefucker\n" +
            "faeces\n" +
            "fag\n" +
            "fagging\n" +
            "faggot\n" +
            "fagot\n" +
            "fannyfucker\n" +
            "fart\n" +
            "farted \n" +
            "farting \n" +
            "farty \n" +
            "fastfuck\n" +
            "fatass\n" +
            "fatfuck\n" +
            "fatfucker\n" +
            "fatso\n" +
            "fckcum\n" +
            "feces\n" +
            "felatio \n" +
            "felch\n" +
            "felcher\n" +
            "felching\n" +
            "fellatio\n" +
            "feltch\n" +
            "feltcher\n" +
            "feltching\n" +
            "fetish\n" +
            "fingerfood\n" +
            "fingerfuck \n" +
            "fingerfucked \n" +
            "fingerfucker \n" +
            "fingerfuckers\n" +
            "fingerfucking \n" +
            "fister\n" +
            "fistfuck\n" +
            "fistfucked \n" +
            "fistfucker \n" +
            "fistfucking \n" +
            "fisting\n" +
            "flange\n" +
            "flatulence\n" +
            "fok\n" +
            "footfuck\n" +
            "footfucker\n" +
            "footlicker\n" +
            "forni\n" +
            "fornicate\n" +
            "foursome\n" +
            "fraud\n" +
            "freakfuck\n" +
            "freakyfucker\n" +
            "freefuck\n" +
            "fubar\n" +
            "fuc\n" +
            "fucck\n" +
            "fck\n" +
            "fuck\n" +
            "fucka\n" +
            "fuckable\n" +
            "fuckbag\n" +
            "fuckbuddy\n" +
            "fucked\n" +
            "fuckedup\n" +
            "fucker\n" +
            "fuckers\n" +
            "fuckface\n" +
            "fuckfest\n" +
            "fuckfreak\n" +
            "fuckfriend\n" +
            "fuckhead\n" +
            "fuckher\n" +
            "fuckin\n" +
            "fuckina\n" +
            "fucking\n" +
            "fuckingbitch\n" +
            "fuckinnuts\n" +
            "fuckinright\n" +
            "fuckit\n" +
            "fuckknob\n" +
            "fuckme \n" +
            "fuckmehard\n" +
            "fuckmonkey\n" +
            "fuckoff\n" +
            "fuckpig\n" +
            "fucks\n" +
            "fucktard\n" +
            "fuckwhore\n" +
            "fuckyou\n" +
            "fudgepacker\n" +
            "fugly\n" +
            "fuk\n" +
            "funfuck\n" +
            "fungus\n" +
            "fuuck\n" +
            "gangbang\n" +
            "gangbanged \n" +
            "gangbanger\n" +
            "gangsta\n" +
            "gatorbait\n" +
            "gay\n" +
            "gaymuthafuckinwhore\n" +
            "gaysex \n" +
            "genital\n" +
            "german\n" +
            "gipp\n" +
            "godammit\n" +
            "goddamit\n" +
            "goddammit\n" +
            "goddamn\n" +
            "goddamned\n" +
            "goddamnes\n" +
            "goddamnit\n" +
            "goddamnmuthafucker\n" +
            "goldenshower\n" +
            "gonorrehea\n" +
            "gotohell\n" +
            "goy\n" +
            "goyim\n" +
            "grostulation\n" +
            "gubba\n" +
            "gyp\n" +
            "gypo\n" +
            "gypp\n" +
            "gyppie\n" +
            "gyppo\n" +
            "gyppy\n" +
            "handjob\n" +
            "hardon\n" +
            "harem\n" +
            "headfuck\n" +
            "hebe\n" +
            "heeb\n" +
            "hell\n" +
            "henhouse\n" +
            "herpes\n" +
            "heterosexual\n" +
            "hillbillies\n" +
            "hillbilly\n" +
            "hiscock\n" +
            "hoes\n" +
            "holestuffer\n" +
            "homicide\n" +
            "homo\n" +
            "homobangers\n" +
            "homosexual\n" +
            "hooker\n" +
            "hookers\n" +
            "hooters\n" +
            "hore\n" +
            "horney\n" +
            "horniest\n" +
            "horny\n" +
            "horseshit\n" +
            "hosejob\n" +
            "hotpussy\n" +
            "hottotrot\n" +
            "hymen\n" +
            "hymie\n" +
            "iblowu\n" +
            "idiot\n" +
            "ikey\n" +
            "incest\n" +
            "insest\n" +
            "intercourse\n" +
            "interracial\n" +
            "intheass\n" +
            "inthebuff\n" +
            "itch\n" +
            "jackass\n" +
            "jackoff\n" +
            "jackshit\n" +
            "jacktheripper\n" +
            "japcrap\n" +
            "jebus\n" +
            "jerkoff\n" +
            "jiga\n" +
            "jigaboo\n" +
            "jigg\n" +
            "jigga\n" +
            "jiggabo\n" +
            "jigger \n" +
            "jiggy\n" +
            "jihad\n" +
            "jijjiboo\n" +
            "jimfish\n" +
            "jism\n" +
            "jiz \n" +
            "jizim\n" +
            "jizjuice\n" +
            "jizm \n" +
            "jizz\n" +
            "jizzim\n" +
            "jizzum\n" +
            "juggalo\n" +
            "junglebunny\n" +
            "kigger\n" +
            "kissass\n" +
            "knocker\n" +
            "kock\n" +
            "kondum\n" +
            "koon\n" +
            "kotex\n" +
            "krap\n" +
            "krappy\n" +
            "kraut\n" +
            "kum\n" +
            "kumbubble\n" +
            "kumbullbe\n" +
            "kummer\n" +
            "kumming\n" +
            "kumquat\n" +
            "kums\n" +
            "kunilingus\n" +
            "kunnilingus\n" +
            "kunt\n" +
            "lapdance\n" +
            "lesbain\n" +
            "lesbayn\n" +
            "lesbian\n" +
            "lesbin\n" +
            "lesbo\n" +
            "lez\n" +
            "lezbe\n" +
            "lezbo\n" +
            "lezz\n" +
            "lezzo\n" +
            "libido\n" +
            "licker\n" +
            "lickme\n" +
            "lickmy\n" +
            "lies\n" +
            "limpdick\n" +
            "lingerie\n" +
            "livesex\n" +
            "lolita\n" +
            "lovebone\n" +
            "lovegoo\n" +
            "lovegun\n" +
            "lovejuice\n" +
            "lovemuscle\n" +
            "lovepistol\n" +
            "loverocket\n" +
            "lubejob\n" +
            "luckycammeltoe\n" +
            "lugan\n" +
            "lynch\n" +
            "mafia\n" +
            "manhater\n" +
            "manpaste\n" +
            "marijuana\n" +
            "mastabate\n" +
            "mstrbt\n" +
            "mastabater\n" +
            "masterbate\n" +
            "mastrabator\n" +
            "masturbate\n" +
            "masturbating\n" +
            "mattressprincess\n" +
            "meatbeatter\n" +
            "meatrack\n" +
            "mgger\n" +
            "mggor\n" +
            "mickeyfinn\n" +
            "milf\n" +
            "mockey\n" +
            "mockie\n" +
            "mocky\n" +
            "mofo\n" +
            "moky\n" +
            "molest\n" +
            "molestation\n" +
            "molester\n" +
            "molestor\n" +
            "moneyshot\n" +
            "mooncricket\n" +
            "moron\n" +
            "mosshead\n" +
            "mothafuck\n" +
            "mothafucka\n" +
            "mothafuckaz\n" +
            "mothafucked \n" +
            "mothafucker\n" +
            "mothafuckin\n" +
            "mothafucking \n" +
            "mothafuckings\n" +
            "motherfuck\n" +
            "motherfucked\n" +
            "motherfucker\n" +
            "motherfuckin\n" +
            "motherfucking\n" +
            "motherfuckings\n" +
            "motherlovebone\n" +
            "muffdive\n" +
            "muffdiver\n" +
            "muffindiver\n" +
            "mufflikcer\n" +
            "mulatto\n" +
            "muncher\n" +
            "munt\n" +
            "murderer\n" +
            "narco\n" +
            "nasty\n" +
            "nastybitch\n" +
            "nastyho\n" +
            "nastyslut\n" +
            "nastywhore\n" +
            "necro\n" +
            "negro\n" +
            "negroes\n" +
            "negroid\n" +
            "nig\n" +
            "niger\n" +
            "nigerian\n" +
            "nigerians\n" +
            "nigg\n" +
            "nigga\n" +
            "niggah\n" +
            "niggaracci\n" +
            "niggard\n" +
            "niggarded\n" +
            "niggarding\n" +
            "niggardliness\n" +
            "niggardly\n" +
            "niggards\n" +
            "niggaz\n" +
            "nigger\n" +
            "niggerhead\n" +
            "niggerhole\n" +
            "niggers\n" +
            "niggor\n" +
            "niggur\n" +
            "niglet\n" +
            "nignog\n" +
            "nigr\n" +
            "nigra\n" +
            "nigre\n" +
            "nip\n" +
            "nipple\n" +
            "nipplering\n" +
            "nittit\n" +
            "nlgger\n" +
            "nlggor\n" +
            "nofuckingway\n" +
            "nofckngway\n" +
            "nofuckinway\n" +
            "nofckinway\n" +
            "nook\n" +
            "nookey\n" +
            "nookie\n" +
            "noonan\n" +
            "nooner\n" +
            "nude\n" +
            "nudger\n" +
            "nutfucker\n" +
            "nymph\n" +
            "ontherag\n" +
            "orga\n" +
            "orgasim \n" +
            "orgasm\n" +
            "orgies\n" +
            "orgy\n" +
            "osama\n" +
            "panti\n" +
            "panty\n" +
            "panties\n" +
            "payo\n" +
            "pecker\n" +
            "peckerwood\n" +
            "pee\n" +
            "peehole\n" +
            "peepshow\n" +
            "peepshw\n" +
            "pendy\n" +
            "penetration\n" +
            "fcuk\n" +
            "peni5\n" +
            "penile\n" +
            "penis\n" +
            "penises\n" +
            "penthouse\n" +
            "pervert\n" +
            "phonesex\n" +
            "phuk\n" +
            "phuked\n" +
            "phuking\n" +
            "phukked\n" +
            "phukking\n" +
            "phungky\n" +
            "phuq\n" +
            "pi55\n" +
            "picaninny\n" +
            "piccaninny\n" +
            "pickaninny\n" +
            "pimp\n" +
            "pimped\n" +
            "pimper\n" +
            "pimpjuic\n" +
            "pimpjuice\n" +
            "pimpsimp\n" +
            "pindick\n" +
            "piss\n" +
            "pissed\n" +
            "pisser\n" +
            "pisses \n" +
            "pisshead\n" +
            "pissin \n" +
            "pissing\n" +
            "pissoff \n" +
            "playboy\n" +
            "playgirl\n" +
            "pocha\n" +
            "pocho\n" +
            "pocketpool\n" +
            "pohm\n" +
            "polack\n" +
            "pom\n" +
            "pommie\n" +
            "pommy\n" +
            "poo\n" +
            "poon\n" +
            "poontang\n" +
            "poop\n" +
            "pooper\n" +
            "pooperscooper\n" +
            "pooping\n" +
            "poorwhitetrash\n" +
            "popimp\n" +
            "porchmonkey\n" +
            "porn\n" +
            "pornflick\n" +
            "pornking\n" +
            "porno\n" +
            "pornography\n" +
            "pornprincess\n" +
            "premature\n" +
            "pric\n" +
            "prick\n" +
            "prickhead\n" +
            "prostitute\n" +
            "protestant\n" +
            "pu55i\n" +
            "pu55y\n" +
            "pube\n" +
            "pubic\n" +
            "pubiclice\n" +
            "pud\n" +
            "pudboy\n" +
            "pudd\n" +
            "puddboy\n" +
            "puntang\n" +
            "purinapricness\n" +
            "puss\n" +
            "pussie\n" +
            "pussies\n" +
            "pussy\n" +
            "pussycat\n" +
            "pussyeater\n" +
            "pussyfucker\n" +
            "pussylicker\n" +
            "pussylips\n" +
            "pussylover\n" +
            "pussypounder\n" +
            "pusy\n" +
            "quashie\n" +
            "queef\n" +
            "queer\n" +
            "quim\n" +
            "ra8s\n" +
            "rabbi\n" +
            "racial\n" +
            "racist\n" +
            "radical\n" +
            "radicals\n" +
            "raghead\n" +
            "randy\n" +
            "rape\n" +
            "raped\n" +
            "raper\n" +
            "rapist\n" +
            "rectum\n" +
            "redlight\n" +
            "redneck\n" +
            "reefer\n" +
            "reestie\n" +
            "refugee\n" +
            "rentafuck\n" +
            "republican\n" +
            "ribbed\n" +
            "rigger\n" +
            "rimjob\n" +
            "rimming\n" +
            "robber\n" +
            "rump\n" +
            "sadist\n" +
            "sadom\n" +
            "samckdaddy\n" +
            "sandnigger\n" +
            "satan\n" +
            "scag\n" +
            "scallywag\n" +
            "scat\n" +
            "schlong\n" +
            "scrotum\n" +
            "scrotom\n" +
            "scum\n" +
            "semen\n" +
            "seppo\n" +
            "servant\n" +
            "sex\n" +
            "sexed\n" +
            "sexfarm\n" +
            "sexhound\n" +
            "sexhouse\n" +
            "sexing\n" +
            "sexkitten\n" +
            "sexpot\n" +
            "sexslave\n" +
            "sextogo\n" +
            "sextoy\n" +
            "sextoys\n" +
            "sexual\n" +
            "sexually\n" +
            "sexwhore\n" +
            "sexy\n" +
            "sexymoma\n" +
            "sexy-slim\n" +
            "shag\n" +
            "shagg\n" +
            "shaggin\n" +
            "shagging\n" +
            "shat\n" +
            "shawtypimp\n" +
            "sheeney\n" +
            "shhit\n" +
            "shinola\n" +
            "shit\n" +
            "shitcan\n" +
            "shitdick\n" +
            "shite\n" +
            "shiteater\n" +
            "shited\n" +
            "shitface\n" +
            "shitfaced\n" +
            "shitfit\n" +
            "shitforbrains\n" +
            "shitfuck\n" +
            "shitfucker\n" +
            "shitfull\n" +
            "shithapens\n" +
            "shithappens\n" +
            "shithead\n" +
            "shithouse\n" +
            "shiting\n" +
            "shitlist\n" +
            "shitola\n" +
            "shitoutofluck\n" +
            "shits\n" +
            "shitstain\n" +
            "shitted\n" +
            "shitter\n" +
            "shitting\n" +
            "shitty \n" +
            "shortfuck\n" +
            "sissy\n" +
            "sixtynine\n" +
            "sixtyniner\n" +
            "skank\n" +
            "skankbitch\n" +
            "skankfuck\n" +
            "skankwhore\n" +
            "skanky\n" +
            "skankybitch\n" +
            "skankywhore\n" +
            "skinflute\n" +
            "skum\n" +
            "skumbag\n" +
            "slanteye\n" +
            "slapper\n" +
            "slavedriver\n" +
            "sleezebag\n" +
            "sleezeball\n" +
            "slime\n" +
            "slimeball\n" +
            "slimebucket\n" +
            "slut\n" +
            "sluts\n" +
            "slutt\n" +
            "slutting\n" +
            "slutty\n" +
            "slutwear\n" +
            "slutwhore\n" +
            "smackthemonkey\n" +
            "smut\n" +
            "snot\n" +
            "snownigger\n" +
            "sodom\n" +
            "sodomise\n" +
            "sodomite\n" +
            "sodomize\n" +
            "sodomy\n" +
            "sonofabitch\n" +
            "sonofbitch\n" +
            "spaghettibender\n" +
            "spaghettinigger\n" +
            "spank\n" +
            "spankthemonkey\n" +
            "sperm\n" +
            "sprm\n" +
            "spermacide\n" +
            "spermbag\n" +
            "spermhearder\n" +
            "spermherder\n" +
            "splittail\n" +
            "spooge\n" +
            "spreadeagle\n" +
            "spunk\n" +
            "spunky\n" +
            "stiffy\n" +
            "strapon\n" +
            "stripclub\n" +
            "stupid\n" +
            "stupidfuck\n" +
            "stupidfucker\n" +
            "suck\n" +
            "suckdick\n" +
            "sucker\n" +
            "suckme\n" +
            "suckmyass\n" +
            "suckmydick\n" +
            "suckmytit\n" +
            "suckoff\n" +
            "swallower\n" +
            "syphilis\n" +
            "taboo\n" +
            "tarbaby\n" +
            "tard\n" +
            "terror\n" +
            "terrorist\n" +
            "testes\n" +
            "testicle\n" +
            "testicles\n" +
            "thirdeye\n" +
            "thirdleg\n" +
            "threesome\n" +
            "timbernigger\n" +
            "tit\n" +
            "titbitnipply\n" +
            "titfuck\n" +
            "titfucker\n" +
            "titfuckin\n" +
            "titfucking\n" +
            "titjob\n" +
            "titlicker\n" +
            "titlover\n" +
            "tits\n" +
            "tittie\n" +
            "titties\n" +
            "titty\n" +
            "toilet\n" +
            "tongethruster\n" +
            "tonguethrust\n" +
            "tonguetramp\n" +
            "tosser\n" +
            "trailertrash\n" +
            "tramp\n" +
            "trannie\n" +
            "tranny\n" +
            "transexual\n" +
            "transsexual\n" +
            "transvestite\n" +
            "triplex\n" +
            "trisexual\n" +
            "trot\n" +
            "tunneloflove\n" +
            "turd\n" +
            "twat\n" +
            "twobitwhore\n" +
            "unfuckable\n" +
            "upskirt\n" +
            "uptheass\n" +
            "upthebutt\n" +
            "urinary\n" +
            "urinate\n" +
            "urine\n" +
            "usama\n" +
            "uterus\n" +
            "vagina\n" +
            "vaginal\n" +
            "vibrater\n" +
            "vibrator\n" +
            "virgin\n" +
            "virginbreaker\n" +
            "vulva\n" +
            "wab\n" +
            "wank\n" +
            "wanker\n" +
            "wanking\n" +
            "waysted\n" +
            "weenie\n" +
            "weewee\n" +
            "welcher\n" +
            "wetspot\n" +
            "whacker\n" +
            "whigger\n" +
            "whiskeydick\n" +
            "whiskydick\n" +
            "whitenigger\n" +
            "whitennigger\n" +
            "whitetrash\n" +
            "whiz\n" +
            "whop\n" +
            "whore\n" +
            "whorefucker\n" +
            "whorehouse\n" +
            "wigger\n" +
            "willie\n" +
            "williewanker\n" +
            "willy\n" +
            "wog\n" +
            "wtf\n" +
            "wuss\n" +
            "xtc\n" +
            "yellowoman\n" +
            "yellowomn\n" +
            "zigabo\n" +
            "zipperhead";
    }

    public String getGalistr()
    {
        return galistr;
    }

}
